#! /usr/bin/env bash

aws --profile tooling ec2 describe-instances | jq '.Reservations[].Instances[] | {InstanceId, InstanceType, Name: .Tags[] | select(.Key=="Name").Value, State: .State.Name, Ip: .PublicIpAddress}'
