#! /bin/bash

if [[ $# != 2 ]]
then
  echo "Usage: $(basename $0) <video_id> <task>"
  echo "Example: $(basename $0) abcde video-shot-detection"
  echo ""
  echo "Fetch the latest valid analysis task result for the given video and task"
  exit 1
fi

kctx=`kubectl config current-context`
bucket=aive-$kctx

kubectl exec -i `kubectl get pod -l app=bastion --no-headers=true -o name | cut -d '/' -f 2` -- \
  psql video --csv -c "
    select s.video_id, t.stream_id, t.task, t.version
    from analysis_task t
    join stream s on t.stream_id = s.id
    where (video_id, task) = ('$1', '$2')
  " | tail -1 | tr "," " " | tail -1 | (
    read -e video_id stream_id task version;
      video_id=$(echo ${video_id} | tr -d "-");
      stream_id=$(echo ${stream_id} | tr -d "-");
      aws --profile $kctx \
        s3 cp s3://${bucket}/videos/${video_id}/streams/${stream_id}/analysis/tasks/${task}-${version}.json -
  );
