#! /usr/bin/env bash

if [[ "$@" == "-h" || $# == 0 ]]
then
  echo "Usage: "
	echo "    $(basename $0) <app>"
	echo "    $(basename $0) <app> <command>"
	echo "    $(basename $0) <app> -c"
  echo ""
  echo "Run a command in the first pod of the given app. The naked invocation will start a bash shell. The -c option will print the pod name so it can be used in other commands, like \`kubectl cp <source> \$(kpod analyser -c):<dest>\`."
  exit 1
fi

app=$1
shift

pod=$(kubectl get pod -l app=$app --no-headers=true -o name | cut -d '/' -f 2 | head -n 1)

if [ "$1" == "-c" ]
then
	echo $pod
	exit
fi

args=$@
if [ "$args" == "" ]
then
	args="bash"
fi

kubectl exec -it pod/$pod -- $args
