#! /usr/bin/env bash

if [[ $# != 1 ]]
then
  echo "Usage: $(basename $0) <overlay>"
  echo ""
  echo "Display analysis task status for the given video."
  exit 1
fi

kubectl exec -it `kubectl get pod -l app=bastion --no-headers=true -o name | cut -d '/' -f 2` -- \
  psql video -c "select t.* from analysis_task t join stream s on t.stream_id = s.id where video_id = '$1' order by executed_at";
